### ISSUE TITLE
Consider identicons rendering on server side

### ISSUE THREAD

**Issue by davidyuk** [aeternity/tipping-community-backend#151]
## Significantly reduce bundle size of superhero-ui and superhero-wallet

https://develop.aggregator.z52da5wt.xyz/report.html

![Screenshot 2020-07-24 at 21 59 14](https://user-images.githubusercontent.com/9007851/88389061-1456b900-cdf9-11ea-855c-387137ff3f75.png)

Also, seems that `avataaars` package depends on React 🙁  https://github.com/aeternity/superhero-ui/issues/667

## Simplify integration into third-party services

For instance, `jwt-auth` generates a token that contains user avatar that after then used in Jitsi and so. Would be nice to have a single url like https://raendom-backend.z52da5wt.xyz/profile/image/ak_...  that will return a proper avatar/identicon depending on user address. https://github.com/aeternity/jwt-auth/issues/7

**Comment by kenodressel** [comment]
Is there no way to get a leaner library in the frontend? we can obviously add it to the backend but its nice if we keep as much of the functionality in the client as possible.

**Comment by kenodressel** [comment]
@davidyuk check these libraries, maybe they are what you are looking for:
- https://github.com/jtouzy/vue-avataaar
- https://github.com/orgordin/vuejs-avataaars

**Comment by davidyuk** [comment]
As I got, https://github.com/aeternity/superhero-avatars is supposed to implement that. Though I don't think that we need a separate backend server for that.
