### ISSUE TITLE
Add a swagger file

### ISSUE THREAD

**Issue by davidyuk** [aeternity/tipping-community-backend#155]
To be able to use it with [Swagger](https://github.com/aeternity/aepp-sdk-js/blob/e0166c22d6244884e96480347d47579aadb28c64/es/utils/swagger.js) module from sdk instead of making a file with wrappers of [backend methods](https://github.com/aeternity/superhero-ui/blob/cb50c3ce1f1a5b645a8b8e4bda71cfa7ffaaf88a/src/utils/backend.js) on aepp side.

**Comment by kenodressel** [comment]
I think the backend methods file does a lot more than simply map the urls to methods. Especially in regards to signatures. Not sure if this can be easily done using the swagger mapper.

**Comment by davidyuk** [comment]
Actually, we are moving towards avoiding handling signatures in backend methods file using [backendAuthMixin](https://github.com/aeternity/superhero-ui/blob/7c47e4b29cf4cd87e47e116953eeb438f357786f/src/utils/backendAuthMixin.js) instead: https://github.com/aeternity/superhero-ui/commit/cb50c3ce1f1a5b645a8b8e4bda71cfa7ffaaf88a#diff-7315e9f3017c9cf851b9c9b6683d7049L30-R40

Other complex operations over backend I'm proposing to define in a vuex module: https://github.com/aeternity/superhero-ui/blob/d14dc7b275fbe56d648974a524d5dbff33a88fb5/src/store/modules/backend.js

**Comment by kenodressel** [comment]
I think the vuex way is a great addition, I am not sure why we would need to move the authentication in a mixin and therefore in the components rather than keeping it tied to the backend.

**Comment by davidyuk** [comment]
We did it because of the flow when a challenge should be signed on mobile through deeplinks: the app should be closed completely and reopened with a signed challenge in url params. Those params are received by a page component, and the mixin helps to finalize the request to the backend without the necessity to do that explicitly on the component side. Making a common interface of backend methods allowed to make that mixin not aware of backend structure.

**Comment by kenodressel** [comment]
That sounds good to me. I guess we can move towards the mixin structure then. I would prefer to streamline the API first but we will see how the priorities are.

**Comment by kenodressel** [comment]
A swagger file is now available but there are some limitations to the OpenAPI Specification so it was sometimes hard to accurately describe the endpoint in full details. We will come back to this when we streamline the api

**Comment by davidyuk** [comment]
Great! I know about https://raendom-backend.z52da5wt.xyz/docs/, but where the entire Swagger file is hosted?

**Comment by kenodressel** [comment]
Its currently not exposed. I can expose it though if you need it.

**Comment by davidyuk** [comment]
Yes, would be nice, because the general idea was to use it with Swagger module from sdk. (https://github.com/aeternity/tipping-community-backend/issues/155#issue-673269235)
