### ISSUE TITLE
Create .env file

### ISSUE THREAD

**Issue by mradkov** [aeternity/tipping-community-backend#158]
Can we extract the needed environment variables in `.env` file?

**Comment by kenodressel** [comment]
you mean a file on the production server or here in the repo?

**Comment by thepiwo** [comment]
@mradkov ?

**Comment by mradkov** [comment]
> you mean a file on the production server or here in the repo?

Well here in the repo, so its easier for anyone who wants to run it locally to setup all of the needed config.

**Comment by kenodressel** [comment]
done with docker-compose
