### ISSUE TITLE
update to postgres db

### ISSUE THREAD

**Issue by thepiwo** [aeternity/tipping-community-backend#166]

**Comment by thepiwo** [comment]
use TEXT instead of VARCHAR(255) for bio, comment, urls, errors and location

**Comment by kenodressel** [comment]
Additonal Steps:
1. Remove entry with id 61 from blacklist (duplicate tip id)
1. Remove id column and make tipId column primary key
1. Create initial postgres schema using npm run db:create
1. Migrate data using pgloader
```
# example command
docker run --rm --name pgloader -v "$(pwd)":/root dimitri/pgloader:latest pgloader -v --with dataonly /root/database.sqlite postgres://postgres:postgres@192.168.1.100/postgres
```

**Comment by thepiwo** [comment]
the migration command on top specifies postgres as db, in the PR we now use superhero as database

**Comment by kenodressel** [comment]
Yes its only an example command. I suggest we name the database `superhero`
