### ISSUE TITLE
Backend doesn't return user balances in Fungible Tokens

### ISSUE THREAD

**Issue by stanislav-slavov** [aeternity/tipping-community-backend#194]
The issue occurs periodically in about half an hour after deploy.

**Comment by kenodressel** [comment]
Can you list the endpoints that are problematic including the fields you expect to be populated?

**Comment by stanislav-slavov** [comment]
https://test-tipping.aeternity.art/tokenCache/balances?address=ak_2riC2CarVXtguGTPWLJhrVtjG4vjnZ6yfbP1E8saLwYRYC8KJi

It should return deployed FT where the user address has any balance

<img width="604" alt="Screenshot 2020-10-21 at 13 47 05" src="https://user-images.githubusercontent.com/7085525/96709936-0b4b9880-13a4-11eb-83e0-df15a8ec98cb.png">
