### ISSUE TITLE
Check for Cloudflare protection screen before taking a screenshot

### ISSUE THREAD

**Issue by davidyuk** [aeternity/tipping-community-backend#273]
![Screenshot 2021-02-22 at 10 13 59](https://user-images.githubusercontent.com/9007851/108674662-af7e5100-74f6-11eb-96c8-30c44eab8891.png)
https://develop.aggregator.z52da5wt.xyz/tip/2644_v1

**Comment by kenodressel** [comment]
Since its an anti-bot protection we will now try to wait it out and if it doesn't work, produce no preview at all. See PR #274
