### ISSUE TITLE
Gateway Time-out when awaiting tip/retip

### ISSUE THREAD

**Issue by davidyuk** [aeternity/tipping-community-backend#371]
It seems that tracking of at least v1 tips/retips is broken, we found it by dropping error omitting in https://github.com/aeternity/superhero-ui/pull/1133. From my perspective, these endpoints should never return 504 if it is called right after submitting a tip. As a workaround, I would omit exceptions from there, but fixing it would speed up making a tip/retip.

![](https://user-images.githubusercontent.com/69896204/124757759-97075400-df36-11eb-8fe8-f8274e7bc022.png)

**Comment by ifaouibadi** [comment]
We're facing this issue again, it's taking a long time for the tipping backend to check if tip/retip exists, and it's throwing a Not Found exception while the tip/retip actually gets created and appears in the feed after 2-3mins

**Comment by thepiwo** [comment]
There is supposed to be a timeout after 30s, if we haven't received it by then something is probably wrong or we can't ensure the event hasn't already happened and we missed it. 

For consumers they can choose how to handle this, e.g. by just reloading when there has been a timeout on this endpoint
