### ISSUE TITLE
Query to /event endpoint is slow and not sorted

### ISSUE THREAD

**Issue by kenodressel** [aeternity/tipping-community-backend#405]
https://raendom-backend.z52da5wt.xyz/cache/events/?address=ak_2AVeRypSdS4ZosdKWW1C4avWU4eeC2Yq7oP7guBGy8jkxdYVUy&event=TipWithdrawn

all `time` is `null` and its the main sorting factor.

Reported by @CedrikNikita :)

**Comment by kenodressel** [comment]
Might be related to #406

**Comment by thepiwo** [comment]
seems to be fine now?
