### ISSUE TITLE
Query to /event endpoint returning duplicate transactions

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/tipping-community-backend#406]
https://raendom-backend.z52da5wt.xyz/cache/events/?address=ak_2AVeRypSdS4ZosdKWW1C4avWU4eeC2Yq7oP7guBGy8jkxdYVUy&event=TipWithdrawn

Amount of transactions returned `4833` for this request, but there are only `6` uniq transactions

**Comment by kenodressel** [comment]
solved :)

**Comment by CedrikNikita** [comment]
I think we should close this issue, since you only clean the aftermath, but did not solved the issue behind it.
