### ISSUE TITLE
Replace .chain name queries with pointees endpoint

### ISSUE THREAD

**Issue by kenodressel** [aeternity/tipping-community-backend#434]
https://mainnet.aeternity.io/mdw/v2/names/ak_2HNsyfhFYgByVq8rzn7q4hRbijsa8LP1VN192zZwGm1JRYnB5C/pointees

**Comment by thepiwo** [comment]
as discussed with @kenodressel this will probably not be feasible for the current use-case, doing the lookup in "reverse" could eventually work, but implies a bigger refactoring
