### ISSUE TITLE
Store selected .chain address for user profile

### ISSUE THREAD

**Issue by mradkov** [aeternity/tipping-community-backend#52]
Store the selected .chain address of the user preference to be associated with in the superhero platform.

**Comment by thepiwo** [comment]
@kenodressel is this already developed?

**Comment by mradkov** [comment]
> @kenodressel is this already developed?

This is already developed.

Though I'm facing some difficulties setting the default name via the wallet. Is the API changed by any chance?

**Comment by kenodressel** [comment]
Not that I know of. Check https://github.com/aeternity/tipping-community-backend/blob/master/test/profile.js
